version: 2
snapshot:
  version_template: "{{ .Branch }}-nightly-{{ .ShortCommit }}"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

builds:
  - id: showmethatoken
    binary: showmethatoken
    main: ./cmd/main.go
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64

docker_manifests:
  - name_template: "{{ .Env.DOCKER_REGISTRY }}/{{ .Env.DOCKER_REGISTRY_NAMESPACE }}/showmethatoken:{{ .Tag }}"
    image_templates:
      - "{{ .Env.DOCKER_REGISTRY }}/{{ .Env.DOCKER_REGISTRY_NAMESPACE }}/showmethatoken:{{ .Tag }}-amd64"
      - "{{ .Env.DOCKER_REGISTRY }}/{{ .Env.DOCKER_REGISTRY_NAMESPACE }}/showmethatoken:{{ .Tag }}-arm64"

dockers:
  - ids:
      - showmethatoken
    goarch: amd64
    image_templates:
      - "{{ .Env.DOCKER_REGISTRY }}/{{ .Env.DOCKER_REGISTRY_NAMESPACE }}/showmethatoken:{{ .Tag }}-amd64"
    use: buildx
    dockerfile: ./Dockerfile
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.title=showmethatoken"
      - "--label=org.opencontainers.image.Tag={{.Tag}}"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
  - ids:
      - showmethatoken
    goarch: arm64
    image_templates:
      - "{{ .Env.DOCKER_REGISTRY }}/{{ .Env.DOCKER_REGISTRY_NAMESPACE }}/showmethatoken:{{ .Tag }}-arm64"
    use: buildx
    dockerfile: ./Dockerfile
    build_flag_templates:
      - "--platform=linux/arm64"
      - "--label=org.opencontainers.image.title=showmethatoken"
      - "--label=org.opencontainers.image.Tag={{.Tag}}"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
